### ISSUE TITLE
No GCS connectivity

### ISSUE THREAD

**Issue by talentedbrute** [RosettaDrone/rosettadrone#12]
**Describe the bug**
Using both a Phantom 3 Standard and a Matrice with Rosseta Drone on a Samsung tablet we are getting spotty connection to a GCS. We have tried our own GCS and QGroundControl.  It will work then not work for a while even after multiple reboots of all systems. Basic network connectivity checks out. 

**To Reproduce**
1. Turn on Drone
2. Connect an tablet to the WiFi 
3. Setup the IP for the remote GCS in Rosetta Drone
4. See that no data makes it to the GCS 

**Expected Behavior**
Connection to GCS works constantly 

**Screenshot**
None

**Desktop (please complete the following information):**
 - OS: Phantom 3, Matrice, Android 9.0
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A
 - OS: Android 9
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by The1only** [comment]
Newer had that issue, you might get bad video normally caused by performance lacks on the desktop PC. 
But the telemetry and video ALWAYS show up on the QGC screen. 
However, if you change settings you might need to restart Rosettadrone (it should remember all settings), and remember to do this you MUST use Android settings and force it to stop, or it will stay resident. ( This is only known to be an issue for the video)

This is NOT a general issue, so there must be something with the setup.

**Comment by talentedbrute** [comment]
I will retest with your recommendation but this persisted even after reboots of the gcs, drone, tablet and controller.

**Comment by kripper** [comment]
Probably fixed. Please retest.
