### ISSUE TITLE
Websocket or other protocols for web browser communication

### ISSUE THREAD

**Issue by robbiedood** [RosettaDrone/rosettadrone#25]
Dear rosetta drone friends,

The app is really helpful and fantastic, allowing many android users fly a DJI drone with a Mavlink-based ground control station. So far it works well with QGroundControl. QGroundControl requires local installation, so we were wondering if rosetta drone could work with a browser.

For example, are we able to use js, rest API and websocket, receive / send mavlink messages from / to rosetta drone ?

Hope to hear your expertise.

Best,
-- Luke

**Comment by The1only** [comment]
I normally set up a virtual server in the cloud to enable this. It is posible to comunicate with this virtual pc, then forward the socket to whatever.On Nov 8, 2020 06:44, lukelu0520 <notifications@github.com> wrote:
Dear rosetta drone friends,
The app is really helpful and fantastic, allowing many android users fly a DJI drone with a Mavlink-based ground control station. So far it works well with QGroundControl. QGroundControl requires local installation, so we were wondering if rosetta drone could work with a browser.
For example, are we able to use js and websocket, send / receive mavlink messages to / from rosetta drone.
Hope to hear your expertise.
Best,
-- Luke

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
On Nov 8, 2020 06:44, lukelu0520 <notifications@github.com> wrote:
Dear rosetta drone friends,
The app is really helpful and fantastic, allowing many android users fly a DJI drone with a Mavlink-based ground control station. So far it works well with QGroundControl. QGroundControl requires local installation, so we were wondering if rosetta drone could work with a browser.
For example, are we able to use js and websocket, send / receive mavlink messages to / from rosetta drone.
Hope to hear your expertise.
Best,
-- Luke

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
On Nov 8, 2020 06:44, lukelu0520 <notifications@github.com> wrote:
Dear rosetta drone friends,
The app is really helpful and fantastic, allowing many android users fly a DJI drone with a Mavlink-based ground control station. So far it works well with QGroundControl. QGroundControl requires local installation, so we were wondering if rosetta drone could work with a browser.
For example, are we able to use js and websocket, send / receive mavlink messages to / from rosetta drone.
Hope to hear your expertise.
Best,
-- Luke

**Comment by lukelu520** [comment]
@The1only thanks for your kind reply. We'll start by setting a [mavros](https://github.com/mavlink/mavros) on a cloud server to see if we are able to receive mavlink data from a mobile device (is connected to a DJI remote controller and installed rosettadrone.)

Once these mavlink data is in ROS node, there is ROS library to communicate with web browser. 
We know the above kind of an indirect way. One also found [mavlink-websocket](https://github.com/CopterExpress/mavlink-websocket) github, which proxies mavlink to websocket and vice versa, but there is interval limit requires further validation. 

If you know any package which is able to do it in a better way (for browser-to-mavlink bi-directional communication), feel free to let us know.

Best,
-- Luke
