### ISSUE TITLE
make error: rosettadrone/app/src/main/cpp/dji_video_jni.c:247: error: undefined reference to 'av_parser_close'

### ISSUE THREAD

**Issue by robbiedood** [RosettaDrone/rosettadrone#26]
Dear rosetta drone friends,

We got the error at **Run Build->Make Project** after we created keys.xml and inserted our api key.

`rosettadrone/app/src/main/cpp/dji_video_jni.c:247: error: undefined reference to 'av_parser_close'`
same errors happens in 'av_free' and 'av_free_packet'

Seems like it is related to link error of ffmpeg library, but I do see av_parser_close in cpp/include/libavcodec/avcodec.h and also find cpp/lib/x86/libavcodec.a. 

Maybe we are missing something, hope to hear your expertise.

Best,
-- Luke

ps: Our OS is Ubuntu 18.04 LTS || Android Studio 4.1  || Gradle version 6.5 || Java 15 || rosettadrone of the master branch.

**Comment by lukelu520** [comment]
Problem solved. Root cause: rossettadrone contains large packages (>600MB), and git can not get all of them unless "**Git Large File Storage (LFS)**" is installed.

For friends whom meet the same issue with us, below is the solution:
`1. install git lfs via https://github.com/git-lfs/git-lfs/wiki/Installation`
`2. GIT_SSL_NO_VERIFY=1 git clone https://github.com/The1only/rosettadrone.git`

Before building, please confirm if your rosettadrone is downloaded completely, the folder size should be more than 600MB.

reference: [diux-dev/rosettadrone/issues/24](https://github.com/diux-dev/rosettadrone/issues/24)
