### ISSUE TITLE
no video streamer  show the screen

### ISSUE THREAD

**Issue by zhaocundang** [RosettaDrone/rosettadrone#32]
I　download master and video_work , complie ok , installed apk success, click start button , no video stream show

**Comment by zhaocundang** [comment]
connect usb to joystick

**Comment by The1only** [comment]
We got several good fixes for the video now. I believe we will get ALL DJI drone up working very soon.
I Will check-in in MAVIC PRO later today...

USB Joystick in QGC was tested quite some time back and was working?

**Comment by gsenkowski** [comment]
I think the Joystick in QGC does not work with Rosettadrone 2 because of the handling of MANUAL_CONTROL messages https://mavlink.io/en/messages/common.html#MANUAL_CONTROL . 

https://github.com/The1only/rosettadrone/blob/137552a19f3267cc908ed9fdf82516ec66fc1cbd/app/src/main/java/sq/rogue/rosettadrone/MAVLinkReceiver.java#L282-L286

The bit mask on the end of line 284 `0b0000100000111000` actually masks out all the relevant values.

**Comment by The1only** [comment]
VERIFIED::  If you create a pull request with inverted bits I will accept it. I just tested the Joystick and It was wrong, now it works.


Thank you.

**Comment by The1only** [comment]
Ahhhh shit... I was misled to believe that we could update the cradle version...
We must step back that one... Give me 5 minutes... I am so sorry.

**Comment by The1only** [comment]
If you just change the Gradle file like this the video will work again: ( at least on my system)

classpath 'com.android.tools.build:gradle:3.5.3'

**Comment by The1only** [comment]
Hmm I belive you are right…. I have not tested that in year and it definitely seems wrong…

**Comment by The1only** [comment]
This generally works now, still some issues with Gradel on some systems but we put that in as a separate issue.
